export const LANGUAGES = [
    { code: 'en', label: 'English' },
    { code: 'hi', label: 'हिन्दी' },
    { code: 'kn', label: 'ಕನ್ನಡ' },
];

export const LABELS = {
    en: {
        header:      'EMERGENCY MEDICAL ID',
        bloodGroup:  'Blood Group',
        dob:         'DOB',
        physical:    'Physical Details',
        height:      'Height',
        weight:      'Weight',
        idMark:      'Identification Mark',
        medical:     'Medical Information',
        allergies:   'Allergies',
        conditions:  'Medical Conditions',
        medications: 'Current Medications',
        organDonor:  'Organ Donor',
        bloodDonor:  'Blood Donor Card',
        surgeries:   'Previous Surgeries / Implants',
        emergency:   'Emergency Contacts',
        insurance:   'Insurance',
        provider:    'Provider',
        policy:      'Policy Number',
        vehicle:     'Vehicle Information',
        reg:         'Registration',
        model:       'Model',
        city:        'Home City',
        yes:         'Yes',
        translating: '(translations loading...)',
    },
    hi: {
        header:      'आपातकालीन चिकित्सा पहचान',
        bloodGroup:  'रक्त समूह',
        dob:         'जन्म तिथि',
        physical:    'शारीरिक विवरण',
        height:      'ऊंचाई',
        weight:      'वजन',
        idMark:      'पहचान चिह्न',
        medical:     'चिकित्सा जानकारी',
        allergies:   'एलर्जी',
        conditions:  'चिकित्सा स्थितियाँ',
        medications: 'वर्तमान दवाएं',
        organDonor:  'अंग दाता',
        bloodDonor:  'रक्त दाता कार्ड',
        surgeries:   'पूर्व सर्जरी / प्रत्यारोपण',
        emergency:   'आपातकालीन संपर्क',
        insurance:   'बीमा',
        provider:    'प्रदाता',
        policy:      'पॉलिसी नंबर',
        vehicle:     'वाहन जानकारी',
        reg:         'पंजीकरण',
        model:       'मॉडल',
        city:        'गृह नगर',
        yes:         'हाँ',
        translating: '(अनुवाद लोड हो रहा है...)',
    },
    kn: {
        header:      'ತುರ್ತು ವೈದ್ಯಕೀಯ ಗುರುತಿನ ಚೀಟಿ',
        bloodGroup:  'ರಕ್ತದ ಗುಂಪು',
        dob:         'ಹುಟ್ಟಿದ ದಿನ',
        physical:    'ದೈಹಿಕ ವಿವರಗಳು',
        height:      'ಎತ್ತರ',
        weight:      'ತೂಕ',
        idMark:      'ಗುರುತಿನ ಚಿಹ್ನೆ',
        medical:     'ವೈದ್ಯಕೀಯ ಮಾಹಿತಿ',
        allergies:   'ಅಲರ್ಜಿಗಳು',
        conditions:  'ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿಗಳು',
        medications: 'ಪ್ರಸ್ತುತ ಔಷಧಗಳು',
        organDonor:  'ಅಂಗ ದಾನಿ',
        bloodDonor:  'ರಕ್ತ ದಾನಿ ಕಾರ್ಡ್',
        surgeries:   'ಹಿಂದಿನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ / ಅಳವಡಿಕೆ',
        emergency:   'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
        insurance:   'ವಿಮೆ',
        provider:    'ಪೂರೈಕೆದಾರ',
        policy:      'ಪಾಲಿಸಿ ಸಂಖ್ಯೆ',
        vehicle:     'ವಾಹನ ಮಾಹಿತಿ',
        reg:         'ನೋಂದಣಿ',
        model:       'ಮಾದರಿ',
        city:        'ತವರು ನಗರ',
        yes:         'ಹೌದು',
        translating: '(ಅನುವಾದ ಲೋಡ್ ಆಗುತ್ತಿದೆ...)',
    },
};
