/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InputformRouteImport } from './routes/inputform'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIdRouteImport } from './routes/rider.$id'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as EditIdRouteImport } from './routes/edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InputformRoute = InputformRouteImport.update({
  id: '/inputform',
  path: '/inputform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIdRoute = RiderIdRouteImport.update({
  id: '/rider/$id',
  path: '/rider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inputform': typeof InputformRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/edit/$id': typeof EditIdRoute
  '/result/$id': typeof ResultIdRoute
  '/rider/$id': typeof RiderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inputform': typeof InputformRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/edit/$id': typeof EditIdRoute
  '/result/$id': typeof ResultIdRoute
  '/rider/$id': typeof RiderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inputform': typeof InputformRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/edit/$id': typeof EditIdRoute
  '/result/$id': typeof ResultIdRoute
  '/rider/$id': typeof RiderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inputform'
    | '/login'
    | '/signup'
    | '/edit/$id'
    | '/result/$id'
    | '/rider/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inputform'
    | '/login'
    | '/signup'
    | '/edit/$id'
    | '/result/$id'
    | '/rider/$id'
  id:
    | '__root__'
    | '/'
    | '/inputform'
    | '/login'
    | '/signup'
    | '/edit/$id'
    | '/result/$id'
    | '/rider/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InputformRoute: typeof InputformRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EditIdRoute: typeof EditIdRoute
  ResultIdRoute: typeof ResultIdRoute
  RiderIdRoute: typeof RiderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputform': {
      id: '/inputform'
      path: '/inputform'
      fullPath: '/inputform'
      preLoaderRoute: typeof InputformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/$id': {
      id: '/rider/$id'
      path: '/rider/$id'
      fullPath: '/rider/$id'
      preLoaderRoute: typeof RiderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InputformRoute: InputformRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EditIdRoute: EditIdRoute,
  ResultIdRoute: ResultIdRoute,
  RiderIdRoute: RiderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
